### ISSUE TITLE
[MINOR] "About" pages contain links to old home page

### ISSUE THREAD

**Issue by andeemarks** [javaee/cargotracker#78]
About pages from both the public (/cargo-tracker/public/track.xhtml) and admin (/cargo-tracker/admin/dashboard.xhtml) sites present link to old home page at [https://cargotracker.java.net/](https://cargotracker.java.net/), which is no longer operational - link should probably be to [https://github.com/javaee/cargotracker](https://github.com/javaee/cargotracker).

**Comment by delabassee** [comment]
Fixed in https://github.com/javaee/cargotracker/commit/0ec5c626e0abf78b019dd84b5f1d6276a4d05bb2
